spring:
  application:
    name: hizone-user
  datasource:
    url: jdbc:mysql://localhost:3306/habitat
    username: root
    password: 123456
  jackson:
    property-naming-strategy: SNAKE_CASE
  config:
    import: nacos:hizone-user.yml
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      config:
        import-check:
          enabled: false
    sentinel:
      transport:
        dashboard: localhost:8080
      eager: true
  # data:
  #   redis:
  #     cluster:
  #       nodes:
  #         - 127.0.0.1:7000
  #         - 127.0.0.1:7001
  #         - 127.0.0.1:7002
  #         - 127.0.0.1:7003
  #         - 127.0.0.1:7004
  #         - 127.0.0.1:7005
  #       max-redirects: 3
  #     timeout: 10000ms
  #     lettuce:
  #       pool:
  #         max-active: 8
  #         max-idle: 8
  #         max-wait: 10000ms
  #         min-idle: 0
mybatis:
  configuration:
    map-underscore-to-camel-case: true
static:
  avatar:
    path: services/hizone-user/src/main/resources/avatar/
logging:
  level:
    com.example.feign.UserFeignClient: DEBUG
