spring:
  application:
    name: fenta-post
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      config:
        import-check:
          enabled: false
  datasource:
    url: jdbc:mysql://localhost:3306/habitat
    username: root
    password: 123456
  jackson:
    property-naming-strategy: SNAKE_CASE
mybatis:
  configuration:
    map-underscore-to-camel-case: true
server:
  port: 8081
