spring:
  datasource:
    url: jdbc:mysql://localhost:3306/habitat
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    property-naming-strategy: SNAKE_CASE

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    