spring:
  application:
    name: hizone-comment
  datasource:
    url: jdbc:mysql://localhost:3306/habitat
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    property-naming-strategy: SNAKE_CASE
  config:
    import: nacos:hizone-comment.yml
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      config:
        import-check:
          enabled: true
    sentinel:
      transport:
        dashboard: localhost:8080
      eager: true
mybatis:
  configuration:
    map-underscore-to-camel-case: true
